version: "3.8"
services:
  angular-app:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - 'golang-app'

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  golang-app:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    
